Proj1 citiroc checkbox
tstana/CitirocUI pull request #16
Opened 2021-12-30 10:34 UTC by Joarfo

Made changes according to comments on branch proj1_multiple_asic_cfg.

2021-12-30 20:27 UTC, tstana requested changes
@Joarfo, OK, we're getting there -- thanks for your changes. Please see my inline comments for some improvements that can be made. As usual, feel free to ask any questions.

Finally (sorry for not having replied to [your thread in the other MR](https://github.com/tstana/CitirocUI/pull/13#discussion_r776438022)), to send the `SelectNVMCitirocConf` command, I think the _Firmware_ tab would be the best place to add a textbox and a button for selecting the configuration. You could also envision only having a button and bringing up your NVM Conf Number Select form...

2021-12-30 20:27 UTC, tstana commented on CitirocUI/SlowControl.cs
> +                    if (connectStatus == 1)
No need to make this check here; `sendSC()` -- if you bring back the code you commented out at the top of that method -- should make the check for you.

2021-12-30 20:27 UTC, tstana commented on CitirocUI/SlowControl.cs
> +                    if (sc_sendToNVM != 1)
You can use the `Checked` member of the new checkbox here.

2021-12-30 20:27 UTC, tstana commented on CitirocUI/NVMConfigNumSelect.cs
> +        public static DialogResult InputBox(string title, string promptText, ref string value)
As outlined in `SlowControl.cs`, the `ref string value` could be made a `ref byte value`. I'm not sure if that can be done with a `DialogResult`, but please check.

2021-12-30 20:27 UTC, tstana commented on CitirocUI/SlowControl.cs
> +                }
Considering my comments above, here's how I would see the `if` statement above (disclaimer: it may not compile):

```C#
byte configNo;

if (checkBox_sendToNVM.Checked == true)
{
  if (NVMVConfigNumSelect.InputBox("Select Config Number", "Config Number:", ref configNo) == DialogResult.OK)
  {
    // `configNo` is assumed to be a `byte` here
    string n = Convert.ToString(configNo, 2);
    strSC += strRev(n);
  }
}
```

From here on out, `strSC` should be the right size for sending with whichever command within `sendSC()`.

2022-01-02 15:09 UTC, Joarfo commented on CitirocUI/SlowControl.cs
> +                                    configNo = configNo.PadLeft(8, '0');
The Padleft() is necessary since convert operation above for some reason removes leading zeroes. It may be that other convert commands could be used to get a proper 8-bit number with leading zeroes, but I have yet to find it.

2022-01-02 15:11 UTC, Joarfo commented on CitirocUI/SlowControl.cs
> +                    if (connectStatus == 1)
This was added in response to a comment on the previous PR that suggested that the user should only be prompted for inputs when the board is connected. I.e the user should not go through the process of inputting a configuration number to then find out that the board was not connected. Should I remove it, but it somewhere else or leave it as is?

2022-01-02 15:23 UTC, Joarfo commented on CitirocUI/NVMConfigNumSelect.cs
> +        public static DialogResult InputBox(string title, string promptText, ref string value)
I will look into if this can be done, but I am also thinking that it might be better to change the name of the class entirely. In essence, what it does is it brings up a message box for typing in inputs; this type of user interface could be useful for other UI elements in the future and is not limited to only this situation. Changing its name could add this option for future functions. I was surprised when I didn't see this form interface in the options for the existing function (it probably exists, but I have not found it). What do you think?

2022-01-05 15:42 UTC, tstana commented on CitirocUI/SlowControl.cs
> +                    if (connectStatus == 1)
Right, good point. You could just do:

```C#
if ((checkBox_sendToNVM.Checked == true) && (connectStatus != 1)
{
    button_sendSC.BackColor = Color.LightCoral;
    tmrButtonColor.Enabled = true;
    label_help.Text = "Please configure your connection.";
    return;
}
```

The timer is enabled so it can revert the color of the button and the `return` at the end is needed so you don't go through the rest of the method.

2022-01-05 15:46 UTC, tstana commented on CitirocUI/NVMConfigNumSelect.cs
> +        public static DialogResult InputBox(string title, string promptText, ref string value)
That could be a good idea, yes. However, if we are to make the check that the config ID is not larger than 255 here, it makes sense to have the dedicated form.

2022-01-06 18:37 UTC, Joarfo commented on CitirocUI/Citiroc.Designer.cs
> -            //
Readded this label

2022-01-06 18:43 UTC, Joarfo commented on CitirocUI/SlowControl.cs
> +                                }
Was unable to find a solution to have this check inside the form without also breaking its functionality. Due to other deadlines and courses, finding this solution has been down prioritized and dropped for the time being.

2022-01-06 18:44 UTC, Joarfo commented on CitirocUI/SlowControl.cs
> +            //    return false;
Thanks for pointing this out, forgot to uncomment after running some tests. The check has been re-added.

2022-01-06 18:44 UTC, Joarfo commented on CitirocUI/SlowControl.cs
> -
Re-added this line

2022-01-06 18:46 UTC, Joarfo commented on CitirocUI/SlowControl.cs
> +            string configNo = "";
Moved the declaration. The configNum cannot be a byte as it is sent via sendSC() that does not accept byte as input (the configuration number is appended to strSC which forms the input for sendSC()).

2022-01-06 18:46 UTC, Joarfo commented on CitirocUI/SlowControl.cs
> +        int sc_sendToNVM;
Removed this and used the member instead.

2022-01-06 18:46 UTC, Joarfo commented on CitirocUI/SlowControl.cs
>          private void button_loadSC_Click(object sender, EventArgs e)
Re-added select NVM button and removed all select functionality from load SC

2022-01-06 18:47 UTC, Joarfo commented on CitirocUI/SlowControl.cs
> +                    if (connectStatus == 1)
Changed the connection check according to suggestion.

2022-01-06 18:47 UTC, Joarfo commented on CitirocUI/SlowControl.cs
> +                                    strSC = getSC();
removed strSC = getSC();

2022-01-06 18:49 UTC, Joarfo commented on CitirocUI/NVMConfigNumSelect.cs
> +        public static DialogResult InputBox(string title, string promptText, ref string value)
Changed the name to "InputForm" to better reflect functionality and to add options for using the form for later. Was unable to properly fix value checks inside the form and had to move on to manage other works. The function has to return a string, not a byte, to properly interface with sendSC().

2022-01-06 18:50 UTC, Joarfo commented on CitirocUI/SlowControl.cs
> +                                    configNo = Convert.ToString(Convert.ToInt32(configNo, 10), 2);
Form cannot return a byte because sendSC will not work properly and the implementation would have to change considerably to accomodate.

2022-01-06 18:50 UTC, Joarfo commented on CitirocUI/SlowControl.cs
> +        private void checkBox_sendToNVM_CheckedChanged(object sender, EventArgs e)
Removed event.

2022-01-06 18:51 UTC, Joarfo commented on CitirocUI/SlowControl.cs
> +        private static string strDefSC = "1110111011101110111011101110111011101110111011101110111011101110111011101110111011101110111011101110111011101110111011101110111011101110111011101110111011101
Reverted string to previous declaration.

2022-01-07 17:23 UTC, tstana commented on CitirocUI/SlowControl.cs
> +                                }
OK, I can make the change for you once I'll have access to the hardware.

2022-01-07 17:24 UTC, tstana commented on CitirocUI/NVMConfigNumSelect.cs
> +        public static DialogResult InputBox(string title, string promptText, ref string value)
OK. Will test and resolve once it's fixed.

2022-01-07 17:36 UTC, tstana requested changes
@Joarfo almost there. I've added some more comments. Mainly, the **Select NVM** button should be part of the _Firmware_ pane, as I mentioned previously.

If you do not have time to make these changes, I can do it for you. I anyway would need to test before merging to `master` (I'm guessing you would also not have time for that).

2022-01-07 17:36 UTC, tstana commented on CitirocUI/Citiroc.cs
> +        }
Please move to `Firmware.cs` (the button should be part of the Firmware tab, as indicated previously).

2022-01-07 17:36 UTC, tstana commented on CitirocUI/Connect.cs
> +                button_selectSC.Visible = true;
This is unnecessary; once you move the **Select NVM** button to the _Firmware_ pane, the code handles the inactivation of all controls under the _Proto-CUBES_ tab under the _Firmware_ pane.

2022-01-07 17:36 UTC, tstana commented on CitirocUI/Connect.cs
> +                button_selectSC.Visible = false;
This is unnecessary; once you move the **Select NVM** button to the _Firmware_ pane, the code handles the inactivation of all controls under the _Proto-CUBES_ tab under the _Firmware_ pane.

2022-01-07 17:36 UTC, tstana commented on CitirocUI/SlowControl.cs
> +                            }
In my view, the solution to making the check in the form would have been as easy as moving this code over to `InputForm.cs`. But I can understand if you're swamped with other activities and can make this change myself.

2022-01-07 17:36 UTC, tstana commented on CitirocUI/SlowControl.cs
> +
This code should be moved over to `Firmware.cs`.

2022-01-07 17:36 UTC, tstana commented on CitirocUI/SlowControl.cs
> +                    button_sendSC.BackColor = Color.LightCoral;
`button_selectSC` (otherwise the **Send SC** button gets colored when in fact the **Select NVM** button should be).

2022-01-07 17:36 UTC, tstana commented on CitirocUI/SlowControl.cs
> +                    }
Add coloring of the button green in case of success.

2022-01-07 17:36 UTC, tstana commented on CitirocUI/SlowControl.cs
> +        {
Unnecessary spaces at the end of this function.

2022-01-08 11:45 UTC, Joarfo commented on CitirocUI/SlowControl.cs
> +                                }
Ok I see now what you mean, I was thinking that ideally the form should remain open while the input was of incorrect size or type, and was unable to get that to work. I added the check to the form now.

2022-01-08 11:46 UTC, Joarfo commented on CitirocUI/NVMConfigNumSelect.cs
> +        public static DialogResult InputBox(string title, string promptText, ref string value)
Fixed value and type check inside InputForm().

2022-01-08 11:50 UTC, Joarfo commented on CitirocUI/Citiroc.cs
> +        }
I don't think moving the code to Firmware.cs makes much sense since no other UI element functions in the firmware tab are written here. I kept it in SlowContol.cs for now, but it could be moved to Citiroc.cs since the other firmware UI elements are there, such as button_ClearArduinoSD_Click().

2022-01-08 11:52 UTC, Joarfo commented on CitirocUI/SlowControl.cs
> +                            }
Indeed that was a solution. Now the same functionality is implented in the InputForm(). I was thinking that ideally, the form should remain open while input is invalid, and was unable to get that to work.

2022-01-08 11:52 UTC, Joarfo commented on CitirocUI/SlowControl.cs
> +
I think keeping it in SlowControl.cs or moving it to Citiroc.cs makes more sense.

2022-01-08 11:58 UTC, Joarfo commented
I addressed all comments left here. I am wondering about where to put button_selectSC_click(), since it feels out of place in Firmware.cs since no other UI elements are written there. SlowControl.cs or Citiroc.cs would be more fitting I think. As for testing, I don't think I will have time to test the latest commit, but I did test right after I re-added the checkbox, and it worked then.

2022-01-08 16:24 UTC, tstana commented on CitirocUI/Citiroc.cs
> +        }
Right, good point! I now remembered looking at the code of `Firmware.cs` that (misleading as it may be) this file contains another class which actually handles communication to the FPGA firmware running on the Citiroc Eval Kit...

2022-01-08 16:27 UTC, tstana commented on CitirocUI/SlowControl.cs
> +
You're right. Let us move it to `Citiroc.cs`, right after the code of `button_ClearArduinoSD_Click()`.

2022-01-08 16:55 UTC, tstana commented on CitirocUI/InputForm.cs
> +                else
... remove this `else` here...

2022-01-08 16:55 UTC, tstana commented on CitirocUI/InputForm.cs
> +            try
This `try` statement can be put in the context of a `while` loop, e.g.:

`while (excep)`

2022-01-08 16:55 UTC, tstana commented on CitirocUI/InputForm.cs
> +                    dialogResult = DialogResult.Cancel;
here we could do:

```C#
throw new SomeTypeOfException("Error message...");
```

**TODO:** Find the right exception to throw from [this list](https://docs.microsoft.com/en-us/dotnet/api/system.exception?view=net-6.0#choosing-standard-exceptions). For example, `ArgumentException` might be a good one to pick.

2022-01-08 16:55 UTC, tstana commented on CitirocUI/InputForm.cs
> +                dialogResult = DialogResult.Cancel;
... and remove this guy here.

2022-01-08 16:55 UTC, tstana commented on CitirocUI/SlowControl.cs
> +
This part of the text should be removed, as it is informing the user that they should configure their connection, when they are simply attempting to send a config to the ASIC.

2022-01-08 16:55 UTC, tstana commented on CitirocUI/SlowControl.cs
> +                                }
Thanks for adding the check in the form. Closing this thread, refer to the comments in the code of the form for hints on how to keep the user in the form for as long as they are typing a wrong value.

2022-01-08 17:16 UTC, tstana requested changes
@Joarfo thank you for your patience to add yet more changes!

You can find some suggestions in-line in the input form on how one could keep the user in the form until they type in a correct value.

One problematic item when testing is that the config cannot be sent to the NVM, as there is a check inside `sendSC()` for the length of the config, which fails when we add our own config. The culprit lines within `sendSC()` are:

```c#
            // Get standard length of slow control bitstream
            int scLength = strDefSC.Length;
            // Get length of current slow control bitstream
            int intLenStrSC = strSC.Length;
            byte[] bytSC = new byte[scLength / 8];
            // If the length of the current bitstream is not OK, return false
            // else store the slow control in byte array
            if (intLenStrSC == scLength)
            {
```

This check can safely be removed, as far as I can see. At the same time, the following should be removed:

- [ ] the definition of the variable `scLength` (use `strSC.Length` in its stead);
- [ ] the definition of the variable `intLenStrSC`.

@Joarfo, will you be able to make these changes and come to the office to try them out on the hardware?

2022-01-08 17:17 UTC, tstana commented on CitirocUI/InputForm.cs
> +                if (Convert.ToInt32(textBox.Text, 10) > 255)
Use `Convert.ToUInt32` here, as this allows for the possibility of the user typing in a negative number.

2022-01-08 21:37 UTC, Joarfo commented
I redid the entire ConfigIdInputForm using Visual Studios tools. Now it checks for correct data type and correct size without removing the user from the form. I also removed the unnecessary check from the sendSC() function. I could come in and test this new command sometime this week probably. I need to return the key anyway.

2022-01-10 11:33 UTC, tstana commented on CitirocUI/CitirocUI.csproj
> +    </Compile>
The `ConfigInputForm.cs` file needs to be removed from the project, otherwise a build error occurs (on my side at least).

2022-01-10 11:35 UTC, tstana commented on CitirocUI/ConfigIdInputForm.cs
> +                    label.Text = "Input to large! Must be below 255";
Input _too_ large (one 'o' missing).

2022-01-10 11:41 UTC, tstana requested changes
@Joarfo, I think it will work now, looking forward to hear the results of the testing!

Please see the remaining comments for things still to be addressed.

2022-01-10 11:41 UTC, tstana commented on CitirocUI/SlowControl.cs
> +                if ((checkBox_sendToNVM.Checked == true) & (connectStatus != 1))
Logical AND needed here, i.e., `&&`.

2022-01-13 10:17 UTC, tstana approved these changes
@Joarfo, it looks good now! Once you confirm it's working after testing, we can merge this PR.

2022-10-22 20:16 UTC, tstana commented on CitirocUI/ConfigIdInputForm.cs
> +                    label.Text = "Input to large! Must be below 255";
Solved in a newer version of `ConfigIdInputForm`.

2022-10-23 18:31 UTC, merged